[package]
description = "Support for rust-i18n crate."
edition = { workspace = true }
license = { workspace = true }
name = "rust-i18n-support"
readme = "../../README.md"
repository = { workspace = true }
version = { workspace = true }

[features]
codegen = [
    "dep:serde",
    "dep:serde_json",
    "dep:serde-saphyr",
    "dep:toml",
    "dep:globwalk",
    "dep:normpath",
]

[dependencies]
arc-swap.workspace = true
base62.workspace = true
proc-macro2.workspace = true
siphasher.workspace = true
regex.workspace = true
triomphe.workspace = true

# codegen-only deps
serde = { workspace = true, optional = true }
serde-saphyr = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
globwalk = { workspace = true, optional = true }
normpath = { workspace = true, optional = true }
