[package]
authors = ["Jason Lee <huacnlee@gmail.com>"]
build = "build.rs"
categories = ["localization", "internationalization"]
description = "Rust I18n is use Rust codegen for load YAML file storage translations on compile time, and give you a t! macro for simply get translation texts."
edition = "2021"
exclude = ["crates", "tests"]
keywords = [
    "gettext",
    "i18n",
    "internationalization",
    "localization",
    "translation",
]
license = "MIT"
name = "rust-i18n"
readme = "README.md"
repository = "https://github.com/longbridge/rust-i18n"
version = "4.0.0-preview1"

[workspace.dependencies]
anyhow = "1"
arc-swap = "1.6.0"
base62 = "2.0.2"
clap = { version = "4.1.14", features = ["derive"] }
criterion = "0.8"
foo = { path = "examples/foo" }
glob = "0.3"
globwalk = "0.9"
ignore = "0.4"
indoc = "2.0"
inventory = "0.3"
log = "0.4"
normpath = "1.1"
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1.0"
regex = "1"
rust-i18n = { path = "." }
rust-i18n-extract = { path = "./crates/extract", version = "4.0.0-preview1" }
rust-i18n-macro = { path = "./crates/macro", version = "4.0.0-preview1" }
rust-i18n-support = { path = "./crates/support", version = "4.0.0-preview1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
siphasher = "1.0"
smallvec = "1.12"
syn = { version = "2.0", features = ["full", "extra-traits"] }
toml = "0.9"
triomphe = { version = "0.1.11", features = ["arc-swap"] }

[dependencies]
log = { workspace = true, optional = true }
inventory.workspace = true
rust-i18n-support.workspace = true
rust-i18n-macro.workspace = true
smallvec.workspace = true

[dev-dependencies]
foo.workspace = true
criterion.workspace = true
no-init-dep = { path = "tests/no-init-dep" }
serde_yaml.workspace = true

[build-dependencies]
globwalk.workspace = true
regex.workspace = true

[features]
log-miss-tr = ["dep:log", "rust-i18n-macro/log-miss-tr"]

[[example]]
name = "app"
test = true

[workspace]
members = [
    "crates/cli",
    "crates/extract",
    "crates/support",
    "crates/macro",
    "examples/app-egui",
    "examples/app-load-path",
    "examples/app-metadata",
    "examples/app-minify-key",
    "examples/foo",
]

[[bench]]
harness = false
name = "bench"

[[bench]]
harness = false
name = "minify_key"
