[package]
description = "cargo-i18n tool for the rust-i18n crate."
edition = "2021"
license = "MIT"
name = "rust-i18n-cli"
readme = "../../README.md"
repository = "https://github.com/longbridge/rust-i18n"
version = "4.0.0-preview1"

[dependencies]
anyhow.workspace = true
clap.workspace = true
globwalk.workspace = true
rust-i18n-support.workspace = true
rust-i18n-extract.workspace = true
serde_json = { features = ["preserve_order"], workspace = true }
serde_yaml.workspace = true
toml.workspace = true

anstyle = "1.0"
csv = "1.3"
indexmap = "2.2"
normpath = "1.2"

[[bin]]
name = "cargo-i18n"
path = "src/main.rs"
